### ISSUE TITLE
Provide an option that allows to 'add all access points for network x as trusted for the following y minutes''

### ISSUE THREAD

**Issue by BramBonne** [BramBonne/privacypolice#12]
As proposed in an e-mail by Denilson Sá:

> An airport is a large location, thus it is covered by several access points with the same name. It is also a place where people walk around a lot. This means that I walk 10m and I get a question from your app and the Wi-Fi disconnects.
> 
> A solution for this could be an option/button/whatever that let's the user say "auto-add all hot spots with the same name for the next hour". Since the user will be around for quite some time, and for sure it will hop from one access point to another (but with the same name), it makes sense to let the app consider all of them as valid ones. The same UX can be applied whenever there is a large area, such as in a Mall.
> 
> (of course, the time of "1 hour" could be selected by the user, but I know making the time adjustable makes the interface harder to design)

**Comment by benedetto** [comment]
While I somehow appreciate the convenience aspect I wonder if this isn't contradicting the security intention of the app. If I get it right, then the extended functionality (connect only to known access points) is based on the idea that people are sitting around somewhere and provide a fake access point with a widely used name (the Starbucks APs come to mind) to trap devices into connecting to this seemingly known network where they then can eavesdrop their online connections?

If I was an attacker, huge buildings like airports or train stations that by design need to have lots of access points spread all over the place would be one of my favourite places. In such places nobody would care about their device switching access points while roaming through the building and running a fake AP there would not be conspicuous.

Implementing such an option would look to me like drilling some really big holes into the safety concept.

**Comment by BramBonne** [comment]
Hi Benedetto,

I definitely appreciate your concern! Should this functionality be implemented, it will definitely need to be an optional feature (which is only enabled for a certain period when the user asks for it). I agree with you that it somewhat nullifies the protection measures implemented in PrivacyPolice. However, the alternative (disabling 'data protection' for a chosen period) requires the user to remember that he/she disabled the functionality, and to re-enable it afterwards.

Don't hesitate to provide more input in this issue, as it will definitely take a while before I've got some time to work on it.

**Comment by nu11point3r** [comment]
Maybe a method such as pinging a known captive portal server after connecting to a new AP to determine whether that particular AP is legitimate would solve this problem.

**Comment by BramBonne** [comment]
I'm afraid that would be just as easy to spoof for an attacker as the network itself.

**Comment by BramBonne** [comment]
Not adding this, based on @benedetto's rationale, and on keeping the app as simple as possible.
