### ISSUE TITLE
Hidden SSID network not blocked by app

### ISSUE THREAD

**Issue by Taomyn** [BramBonne/privacypolice#18]
I installed the app on my two devices, N5 and N6, where one connects to our work Guest network and the other to our Private network. The private network is a hidden SSID.

When I first ran the app on the guest network it was immediately blocked as expected, and I authorised it. However on the phone connecting to the private network the app has simply ignored it and connects without needing to be authorised.

Is this as designed or a bug?

**Comment by BramBonne** [comment]
Hi Taomyn,

This is indeed by design. For cloaked (hidden) networks, it is impossible to see whether the network is in range without sending a directed probe request. For this reason, the network needs to be enabled.

However, may I suggest that cloaking a network does not really add anything to security? It has been [widely documented](http://lib.tkk.fi/Diss/2009/isbn9789512299034/article4.pdf) that cloaking the network essentially shifts the problem from the access point to the station.

Best,
Bram

**Comment by Taomyn** [comment]
Yeah I know, but our network team doesn't seem to get it even though it causes issues they won't listen.

Thanks for the information.
