### ISSUE TITLE
What's the purpose of GPS permission?

### ISSUE THREAD

**Issue by eridal** [BramBonne/privacypolice#24]
Honest question, as this is preventing me to upgrade to latest.

**Comment by BramBonne** [comment]
Hi Martin,

Quoting the Google Play listing:
> PrivacyPolice now requires the location permission to run. This is because Android 6.0 does not allow access to the list of Wi-Fi networks without this location. PrivacyPolice will *never* collect your information. Please consult the source code at https://github.com/BramBonne/privacypolice if you have any doubts.

In short, Android 6.0 (Marshmallow) considers access to the currently available Wi-Fi networks as a location permission, since it can be used to pretty accurately determine your location.

Hope this answers your question. If you still have any doubts, feel free to reopen this issue.

**Comment by eridal** [comment]
Oh I didn't know that. 

I've reading the source code and couldn't find anything related to that permission. Now it makes sense.

Thanks for clarifying

**Comment by eridal** [comment]
As a side note, I've installed from fdroid. 

It could be handy to include that note in there as well.

**Comment by BramBonne** [comment]
Thanks for the tip! I'll update it in the README file on Github, hoping that F-Droid will pull my updates from there :-)

**Comment by eridal** [comment]
I've learn that fdroid has a repo with all the app's metadata. Here's the privacypolice one:

> https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/be.uhasselt.privacypolice.txt

It's still not clear how that gets updated to me, but hope it helps we to find out
