### ISSUE TITLE
Suggestion: Add features of WiFi Protector

### ISSUE THREAD

**Issue by SecUpwN** [BramBonne/privacypolice#34]
Good morning @BramBonne, I am currently using two apps managing WiFi networks: Your great `Wi-Fi Privacy Police` and another app that I used much longer than yours: [Wifi Protector](http://forum.xda-developers.com/showthread.php?t=1350941), which unfortunately was not open source and ceased development. I would love your open source app to adopt these features so that I can finally uninstall that old closed-source and unmaintained app. Thank you so much!

**Comment by BramBonne** [comment]
Hi @SecUpwN !

Thanks for the link to Wifi Protector! It looks like a very handy app. I won't be including its functionality due to two reasons, though:

1. I want to keep PrivacyPolice limited to just one function, leaving other functionality up to other apps.
2. The source code of Wifi Protector doesn't seem to be publicly available.

Thanks for your input!
Bram
