### ISSUE TITLE
Provider supplied wifi

### ISSUE THREAD

**Issue by mxa** [BramBonne/privacypolice#36]
In Korea the network providers provide free complimentary wifi with data plans to help you cut down on 4g usage. The implementation is a bit strange though. It is an open wifi available almost anywhere, and you need to register your device wlan adapter MAC address. Because it is available almost everywhere it isn't usable with privacypolice. Unless there would be a way to whitelist a wifi so it would connect to it anywhere. Which would somewhat defeat the idea of privacypolice. What do you think?

**Comment by BramBonne** [comment]
Hi mxa,

I'm not implementing this because of the reasons you already mentioned. Having this implemented would essentially negate the entire security of the second option (data protection). If you want, you can always disable this option to have the same desired effect.

See https://github.com/BramBonne/privacypolice/issues/6 for a further rationale.
