### ISSUE TITLE
Layout of the main screen a bit weird

### ISSUE THREAD

**Issue by LaGlobule** [BramBonne/privacypolice#9]
Look at this screenshot.
![screenshot_2015-03-16-13-37-11](https://cloud.githubusercontent.com/assets/11502502/6666418/8700b66c-cbe4-11e4-87f6-59f3bfc2a203.png)

As you can see, there is many unused space around the two switches and the text is rather tight in a small column.
May be you've got this behaviour on other devices.
It is not very annoying but could it be fixed ?

For information, I'm using a Samsung Galaxy S2 with JB v4.1.2 stock ROM.
Thanks for taking this case into account.

**Comment by BramBonne** [comment]
Hi! Thanks for your comment!

That screen does indeed look rather ugly. Unfortunately, I'm using the default Android implementation of a SwitchPreference here (together with its default Layout as defined by the OS), as you can see here: https://github.com/BramBonne/privacypolice/blob/master/privacypolice/src/main/java/be/uhasselt/privacypolice/PreferencesActivity.java

If this issue is prevalent enough (as in: if it also occurs on other devices) I could probably revert the SwitchPreference back to its old 'CheckboxPreference' variant. I encourage anyone encountering the same problem to comment on this issue, to allow me to get an idea of how many devices are affected.

**Comment by BramBonne** [comment]
Using new layout since version 2.0. Please re-open this bug if the problem persists.
